//>>built
require({cache:{"dojo/store/Cache":function(){define(["../_base/lang","../_base/Deferred"],function(t,r){var s=function(h,e,n){n=n||{};return t.delegate(h,{query:function(w,m){var f=h.query(w,m);f.forEach(function(c){(!n.isLoaded||n.isLoaded(c))&&e.put(c)});return f},queryEngine:h.queryEngine||e.queryEngine,get:function(n,m){return r.when(e.get(n),function(f){return f||r.when(h.get(n,m),function(c){c&&e.put(c,{id:n});return c})})},add:function(n,m){return r.when(h.add(n,m),function(f){e.add("object"==
typeof f?f:n,m);return f})},put:function(n,m){e.remove(m&&m.id||this.getIdentity(n));return r.when(h.put(n,m),function(f){e.put("object"==typeof f?f:n,m);return f})},remove:function(n,m){return r.when(h.remove(n,m),function(f){return e.remove(n,m)})},evict:function(h){return e.remove(h)}})};t.setObject("dojo.store.Cache",s);return s})},"dojo/store/Memory":function(){define(["../_base/declare","./util/QueryResults","./util/SimpleQueryEngine"],function(t,r,s){return t("dojo.store.Memory",null,{constructor:function(h){for(var e in h)this[e]=
h[e];this.setData(this.data||[])},data:null,idProperty:"id",index:null,queryEngine:s,get:function(h){return this.data[this.index[h]]},getIdentity:function(h){return h[this.idProperty]},put:function(h,e){var n=this.data,r=this.index,m=this.idProperty,m=h[m]=e&&"id"in e?e.id:m in h?h[m]:Math.random();if(m in r){if(e&&!1===e.overwrite)throw Error("Object already exists");n[r[m]]=h}else r[m]=n.push(h)-1;return m},add:function(h,e){(e=e||{}).overwrite=!1;return this.put(h,e)},remove:function(h){var e=
this.index,n=this.data;if(h in e)return n.splice(e[h],1),this.setData(n),!0},query:function(h,e){return r(this.queryEngine(h,e)(this.data))},setData:function(h){h.items?(this.idProperty=h.identifier,h=this.data=h.items):this.data=h;this.index={};for(var e=0,n=h.length;e<n;e++)this.index[h[e][this.idProperty]]=e}})})},"dojo/store/util/SimpleQueryEngine":function(){define(["../../_base/array"],function(t){return function(r,s){function h(e){e=t.filter(e,r);var h=s&&s.sort;h&&e.sort("function"==typeof h?
h:function(m,c){for(var b,a=0;b=h[a];a++){var p=m[b.attribute],g=c[b.attribute];if(p!=g)return!!b.descending==(null==p||p>g)?-1:1}return 0});if(s&&(s.start||s.count)){var m=e.length;e=e.slice(s.start||0,(s.start||0)+(s.count||Infinity));e.total=m}return e}switch(typeof r){default:throw Error("Can not query with a "+typeof r);case "object":case "undefined":var e=r;r=function(h){for(var r in e){var m=e[r];if(m&&m.test){if(!m.test(h[r],h))return!1}else if(m!=h[r])return!1}return!0};break;case "string":if(!this[r])throw Error("No filter function "+
r+" was found in store");r=this[r];case "function":}h.matches=r;return h}})},"dgrid/OnDemandGrid":function(){define(["dojo/_base/declare","./Grid","./OnDemandList"],function(t,r,s){return t([r,s],{})})},"dgrid/Grid":function(){define("dojo/_base/kernel dojo/_base/declare dojo/on dojo/has put-selector/put ./List dojo/_base/sniff".split(" "),function(t,r,s,h,e,n){function w(c,b){b&&b.nodeType&&c.appendChild(b)}var m=8>h("ie")&&!0,f=/[^\._a-zA-Z0-9-]/g;r=r(n,{columns:null,cellNavigation:!0,tabableHeader:!0,
showHeader:!0,column:function(c){return"string"==typeof c?this.columns[c]:this.cell(c).column},listType:"grid",cell:function(c,b){if(c.row&&c.row instanceof this._Row)return c;c.target&&c.target.nodeType&&(c=c.target);var a;if(c.nodeType){do{if(this._rowIdToObject[c.id])break;var p=c.columnId;if(p){b=p;a=c;break}c=c.parentNode}while(c&&c!=this.domNode)}if(!a&&"undefined"!=typeof b){var g=this.row(c);if(p=g.element)for(var p=p.getElementsByTagName("td"),d=0;d<p.length;d++)if(p[d].columnId==b){a=p[d];
break}}if(null!=c)return{row:g||this.row(c),column:b&&this.column(b),element:a}},_columnsCss:function(c){c.fullSelector=function(){return this.parent.fullSelector()+" .dgrid-cell"};for(var b=0;b<c.children.length;b++){var a=c.children[b];a.field=a.className=a.selector.substring(1)}return c.children},createRowCells:function(c,b,a){var p=e("table.dgrid-row-table[role\x3dpresentation]"),g=9>h("ie")?e(p,"tbody"):p,d,u,q,v,y,z,l,k,A,x;a=a||this.subRows;u=0;for(q=a.length;u<q;u++){z=a[u];d=1==q&&!h("ie")?
g:e(g,"tr");z.className&&e(d,"."+z.className);v=0;for(y=z.length;v<y;v++){l=z[v];k=l.id;A=l.className||l.field&&"field-"+l.field;A=e(c+(".dgrid-cell.dgrid-cell-padding"+(k?".dgrid-column-"+k:"")+(A?"."+A:"")).replace(f,"-")+"[role\x3d"+("th"===c?"columnheader":"gridcell")+"]");A.columnId=k;m?(k=e(A,"!dgrid-cell-padding div.dgrid-cell-padding"),A.contents=k):k=A;if(x=l.colSpan)A.colSpan=x;if(x=l.rowSpan)A.rowSpan=x;b(k,l);d.appendChild(A)}}return p},left:function(c,b){return this.cell(this._move(c,
-(b||1),"dgrid-cell"))},right:function(c,b){return this.cell(this._move(c,b||1,"dgrid-cell"))},renderRow:function(c,b){var a=this.createRowCells("td",function(a,g){var d=c;g.get?d=g.get(c):"field"in g&&"_item"!=g.field&&(d=d[g.field]);g.formatter?a.innerHTML=g.formatter(d):g.renderCell?w(a,g.renderCell(c,d,a,b)):null!=d&&a.appendChild(document.createTextNode(d))},b&&b.subRows);return e("div[role\x3drow]\x3e",a)},renderHeader:function(){var c=this,b=this.headerNode,a=b.childNodes.length;for(b.setAttribute("role",
"row");a--;)e(b.childNodes[a],"!");a=this.createRowCells("th",function(b,a){var c=a.headerNode=b;m&&(b=b.parentNode);var f=a.field;f&&(b.field=f);if(a.renderHeaderCell)w(c,a.renderHeaderCell(c));else if(a.label||a.field)c.appendChild(document.createTextNode(a.label||a.field));!1!==a.sortable&&(f&&"_item"!=f)&&(b.sortable=!0,b.className+=" dgrid-sortable")},this.subRows&&this.subRows.headerRows);this._rowIdToObject[a.id=this.id+"-header"]=this.columns;b.appendChild(a);s(a,"click,keydown",function(a){if("click"==
a.type||32==a.keyCode||13==a.keyCode){a=a.target;var g,d;do if(a.sortable)return c._sortNode=a,a=a.field||a.columnId,g=(d=c._sort[0])&&d.attribute==a&&!d.descending,c.set("sort",a,g);while((a=a.parentNode)&&a!=b)}})},resize:function(){var c=this.headerNode.firstChild,b=this.contentNode,a;this.inherited(arguments);if(!h("ie")||7<h("ie"))if(b.style.width="",b&&c&&(a=c.offsetWidth)!=b.offsetWidth)b.style.width=a+"px"},destroy:function(){this._destroyColumns();this.inherited(arguments)},_setSort:function(c,
b){this.inherited(arguments);this._lastSortedArrow&&(e(this._lastSortedArrow,"\x3c!dgrid-sort-up!dgrid-sort-down"),e(this._lastSortedArrow,"!"),delete this._lastSortedArrow);if(this._sort[0]){var a=this._sort[0].attribute,m=this._sort[0].descending,g=this._sortNode,d,f,h;delete this._sortNode;if(!g)for(h in d=this.columns,d)if(f=d[h],f.field==a){g=f.headerNode;break}g&&(g=g.contents||g,this._lastSortedArrow=e(g.firstChild,"-div.dgrid-sort-arrow.ui-icon[role\x3dpresentation]"),this._lastSortedArrow.innerHTML=
"\x26nbsp;",e(g,m?".dgrid-sort-down":".dgrid-sort-up"),this.resize())}},styleColumn:function(c,b){return this.addCssRule("#"+this.domNode.id+" .dgrid-column-"+c,b)},_configColumns:function(c,b){var a=[],m=b instanceof Array,g,d;for(g in b)d=b[g],"string"==typeof d&&(b[g]=d={label:d}),!m&&!d.field&&(d.field=g),g=d.id=d.id||(isNaN(g)?g:c+g),c&&(this.columns[g]=d),this._configColumn&&this._configColumn(d,g,b,c),d.grid=this,"function"===typeof d.init&&d.init(),a.push(d);return m?b:a},_destroyColumns:function(){var c=
this.subRows.length,b,a,m,g;this.cleanup();for(b=0;b<c;b++){a=0;for(g=this.subRows[b].length;a<g;a++)m=this.subRows[b][a],"function"===typeof m.destroy&&m.destroy()}},configStructure:function(){var c=this.subRows;if(c){this.columns={};for(var b=0;b<c.length;b++)c[b]=this._configColumns(b+"-",c[b])}else this.subRows=[this._configColumns("",this.columns)]},_setColumns:function(c){this._destroyColumns();this.subRows=null;this.columns=c;this._updateColumns()},_setSubRows:function(c){this._destroyColumns();
this.subRows=c;this._updateColumns()},setColumns:function(c){t.deprecated("setColumns(...)",'use set("columns", ...) instead',"dgrid 1.0");this.set("columns",c)},setSubRows:function(c){t.deprecated("setSubRows(...)",'use set("subRows", ...) instead',"dgrid 1.0");this.set("subRows",c)},_updateColumns:function(){this.configStructure();this.renderHeader();this.refresh();this._lastCollection&&this.renderArray(this._lastCollection);this.resize()}});r.appendIfNode=w;r.defaultRenderCell=function(c,b,a,m){null!=
b&&a.appendChild(document.createTextNode(b))};return r})},"put-selector/put":function(){(function(t){var r,s=/[-+,> ]/;t([],r=function(h,e){function n(f){function c(){d&&(g&&d!=g)&&(g==f&&(b||(b=s.test(y)&&h.createDocumentFragment()))||g).insertBefore(d,e||null)}for(var b,a,e,g,d,u=arguments,q=u[0],v=0;v<u.length;v++){var y=u[v];if("object"==typeof y){a=!1;if(y instanceof Array){d=h.createDocumentFragment();for(var z=0;z<y.length;z++)d.appendChild(n(y[z]));y=d}if(y.nodeType)d=y,c(),g=y,e=0;else for(z in y)d[z]=
y[z]}else if(a)a=!1,d.appendChild(h.createTextNode(y));else{1>v&&(f=null);a=!0;if(q=y.replace(t,function(l,k,a,b,z,q){k&&(c(),"-"==k||"+"==k?(g=(e=d||g).parentNode,d=null,"+"==k&&(e=e.nextSibling)):("\x3c"==k?g=d=(d||g).parentNode:(","==k?g=f:d&&(g=d),d=null),e=0),d&&(g=d));if((l=!a&&b)||!d&&(a||z))"$"==l?(l=u[++v],g.appendChild(h.createTextNode(l))):(l=l||n.defaultTag,(k=m&&u[v+1]&&u[v+1].name)&&(l="\x3c"+l+' name\x3d"'+k+'"\x3e'),d=h.createElement(l));a&&("$"==b&&(b=u[++v]),"#"==a?d.id=b:(k=(l=
d.className)&&(" "+l+" ").replace(" "+b+" "," "),"."==a?d.className=l?(k+b).substring(1):b:"!"==y?n("div",d,"\x3c").innerHTML="":(k=k.substring(1,k.length-1),k!=l&&(d.className=k))));if(z)if("$"==q&&(q=u[++v]),"style"==z)d.style.cssText=q;else d["!"==z.charAt(0)?(z=z.substring(1))&&"removeAttribute":"setAttribute"](z,""===q?z:q);return""}))throw new SyntaxError("Unexpected char "+q+" in "+y);c();g=q=d||g}}f&&b&&f.appendChild(b);return q}s=e||s;var t=/(?:\s*([-+ ,<>]))?\s*(\.|!\.?|#)?([-\w%$]+)?(?:\[([^\]=]+)=?['"]?([^\]'"]*)['"]?\])?/g;
h=h||document;var m="object"==typeof h.createElement;n.defaultTag="div";n.forDocument=r;return n})})("undefined"==typeof define?function(t,r){"undefined"==typeof window?require("./node-html")(module,r):put=r()}:define)},"dgrid/List":function(){define("dojo/_base/array dojo/_base/kernel dojo/_base/declare dojo/on dojo/has ./util/misc dojo/has!touch?./TouchScroll xstyle/has-class put-selector/put dojo/_base/sniff xstyle/css!./css/dgrid.css".split(" "),function(t,r,s,h,e,n,w,m,f){function c(v){var a=
v?"."+v.replace(u,"."):"";this._class&&(a="!"+this._class.replace(u,"!")+a);f(this.domNode,a);this._class=v}function b(){return this._class}m("mozilla","opera","webkit","ie","ie-6","ie-6-7","quirks","no-quirks","touch");var a,p=f(document.getElementsByTagName("head")[0],"style"),g=[],p=p.sheet||p.styleSheet,d=0,u=/ +/g,q=7>e("ie")?function(){var v,a,b;if(this._started&&(v=document.documentElement,a=v.clientWidth,v=v.clientHeight,b=this._prevWinDims||[],b[0]!==a||b[1]!==v))this.resize(),this._prevWinDims=
[a,v]}:function(){this._started&&this.resize()};return s(w?w:null,{tabableHeader:!1,showHeader:!1,showFooter:!1,maintainOddEven:!0,postscript:function(v,a){var b=this;(this._Row=function(l,a,v){this.id=l;this.data=a;this.element=v}).prototype.remove=function(){b.removeRow(this.element)};a&&(this.srcNodeRef=a=a.nodeType?a:document.getElementById(a));this.create(v,a)},listType:"list",create:function(a,b){var g=this.domNode=b||f("div"),l;a?(this.params=a,s.safeMixin(this,a),l=a["class"]||a.className||
g.className,this._sort=a.sort||[],delete this.sort):this._sort=[];this.observers=[];this._listeners=[];this._rowIdToObject={};this.postMixInProperties&&this.postMixInProperties();this.id=g.id=g.id||this.id||"dgrid_"+d++;this.buildRendering();l&&c.call(this,l);this.postCreate&&this.postCreate();delete this.srcNodeRef;this.domNode.offsetHeight&&this.startup()},buildRendering:function(){var a=this.domNode,b=this,c,l,k,g;g=this.isRTL="rtl"==(document.body.dir||document.documentElement.dir||document.body.style.direction).toLowerCase();
a.className="";f(a,"[role\x3dgrid].ui-widget.dgrid.dgrid-"+this.listType);c=this.headerNode=f(a,"div.dgrid-header.dgrid-header-row.ui-widget-header"+(this.showHeader?"":".dgrid-header-hidden"));8>e("ie")&&f(a,"div.dgrid-spacer");l=this.bodyNode=f(a,"div.dgrid-scroller");l.tabIndex=-1;this.headerScrollNode=f(a,"div.dgrid-header-scroll.dgrid-scrollbar-width.ui-widget-header");k=this.footerNode=f("div.dgrid-footer"+(this.showFooter?"":".dgrid-footer-hidden"));f(a,k);g&&(a.className+=" dgrid-rtl"+(e("webkit")?
"":" dgrid-rtl-nonwebkit"));h(l,"scroll",function(k){b.showHeader&&(c.scrollLeft=k.scrollLeft||l.scrollLeft);k.stopPropagation();h.emit(a,"scroll",{scrollTarget:l})});this.configStructure();this.renderHeader();this.contentNode=this.touchNode=f(this.bodyNode,"div.dgrid-content.ui-widget-content");this._listeners.push(this._resizeHandle=h(window,"resize",n.throttleDelayed(q,this)))},startup:function(){this.inherited(arguments);this._started||(this._started=!0,this.resize(),this.set("sort",this._sort))},
configStructure:function(){},resize:function(){var v=this.bodyNode,b=this.headerNode,c=this.footerNode,l=b.offsetHeight,k=this.showFooter?c.offsetHeight:0,g=7>e("ie");this.headerScrollNode.style.height=v.style.marginTop=l+"px";v.style.marginBottom=k+"px";g&&(v.style.height="",v.style.height=Math.max(this.domNode.offsetHeight-l-k,0)+"px",k&&(c.style.bottom="1px",setTimeout(function(){c.style.bottom=""},0)));a||(l=f(document.body,"div.dgrid-scrollbar-measure"),a=l.offsetWidth-l.clientWidth,f(l,"!"),
7===e("ie")&&a++,this.addCssRule(".dgrid-scrollbar-width","width: "+a+"px"),this.addCssRule(".dgrid-scrollbar-height","height: "+a+"px"),17!=a&&!g&&(this.addCssRule(".dgrid-header","right: "+a+"px"),this.addCssRule(".dgrid-rtl-nonwebkit .dgrid-header","left: "+a+"px")));g&&(b.style.width=v.clientWidth+"px",setTimeout(function(){b.scrollLeft=v.scrollLeft},0))},addCssRule:function(a,b){var c=g.length;g[c]=(p.cssRules||p.rules).length;p.addRule?p.addRule(a,b):p.insertRule(a+"{"+b+"}",g[c]);return{remove:function(){var a=
g[c],k,b=g.length;if(void 0!==a){p.deleteRule?p.deleteRule(a):p.removeRule(a);g[c]=void 0;for(k=c;k<b;k++)g[k]>a&&g[k]--}}}},on:function(a,b){var c=h(this.domNode,a,b);e("dom-addeventlistener")||this._listeners.push(c);return c},cleanup:function(){var a=this.observers,b;for(b in this._rowIdToObject)if(this._rowIdToObject[b]!=this.columns){var c=document.getElementById(b);c&&this.removeRow(c,!0)}for(b=0;b<a.length;b++)(c=a[b])&&c.cancel();this.observers=[];this.preload=null},destroy:function(){if(this._listeners){for(var a=
this._listeners.length;a--;)this._listeners[a].remove();delete this._listeners}this.cleanup();f(this.domNode,"!")},refresh:function(){this.cleanup();this._rowIdToObject={};this._autoId=0;this.contentNode.innerHTML="";this.scrollTo({x:0,y:0})},newRow:function(a,b,c,l){if(!b||b.parentNode){var k=this.insertRow(a,b?b.parentNode:this.contentNode,b,l.start+c,l);f(k,".ui-state-highlight");setTimeout(function(){f(k,"!ui-state-highlight")},250);return k}},adjustRowIndices:function(a){if(this.maintainOddEven){var b=
a.rowIndex;if(-1<b){do-1<a.rowIndex&&(-1<(a.className+" ").indexOf("dgrid-row ")&&f(a,"."+(1==b%2?"dgrid-row-odd":"dgrid-row-even")+"!"+(0==b%2?"dgrid-row-odd":"dgrid-row-even")),a.rowIndex=b++);while((a=a.nextSibling)&&a.rowIndex!=b)}}},renderArray:function(a,b,c){function l(a){n=g.insertRow(a,q,null,m++,c);n.observerIndex=h;return n}function k(a){if(e=b?b.parentNode:g.contentNode)e.insertBefore(q,b||null),(n=a[a.length-1])&&g.adjustRowIndices(n);return f=a}c=c||{};var g=this,m=c.start||0,d,f,e;
b||(this._lastCollection=a);if(a.observe)var h=this.observers.push(a.observe(function(a,b,l){var k,v;-1<b&&f[b]&&(d=f.splice(b,1)[0],d.parentNode==e&&((k=d.nextSibling)&&b!=l&&k.rowIndex--,g.removeRow(d)),g._processScroll&&g._processScroll());if(-1<l){v=f[l];if(!v&&(v=f[l-1]))v=(v.connected||v).nextSibling;if(d=g.newRow(a,v,l,c))if(d.observerIndex=h,f.splice(l,0,d),!k||l<b)a=d.previousSibling,k=!a||a.rowIndex+1==d.rowIndex||0==d.rowIndex?d:a;c.count++}b!=l&&k&&g.adjustRowIndices(k)},!0))-1;var q=
document.createDocumentFragment();if(a.map){if(f=a.map(l,console.error),f.then)return f.then(k)}else{f=[];for(var p=0,u=a.length;p<u;p++)f[p]=l(a[p])}var n;return k(f)},renderHeader:function(){},_autoId:0,insertRow:function(a,b,c,l,k){var g=k.parentId,g=this.id+"-row-"+(g?g+"-":"")+(this.store&&this.store.getIdentity?this.store.getIdentity(a):this._autoId++),d=document.getElementById(g),f=d&&d.previousSibling;if(!d||c&&d.parentNode!=c.parentNode)d&&this.removeRow(d),d=this.renderRow(a,k),d.className=
(d.className||"")+" ui-state-default dgrid-row "+(1==l%2?"dgrid-row-odd":"dgrid-row-even"),this._rowIdToObject[d.id=g]=a;b.insertBefore(d,c||null);f&&this.adjustRowIndices(f);d.rowIndex=l;return d},renderRow:function(a,b){return f("div",""+a)},removeRow:function(a,b){a=a.element||a;delete this._rowIdToObject[a.id];b||f(a,"!")},row:function(a){var b;if(a instanceof this._Row)return a;a.target&&a.target.nodeType&&(a=a.target);if(a.nodeType){do{var c=a.id;if(b=this._rowIdToObject[c])return new this._Row(c.substring(this.id.length+
5),b,a);a=a.parentNode}while(a&&a!=this.domNode)}else return"object"==typeof a?b=this.store.getIdentity(a):(b=a,a=this._rowIdToObject[this.id+"-row-"+b]),new this._Row(b,a,document.getElementById(this.id+"-row-"+b))},cell:function(a){return{row:this.row(a)}},_move:function(a,b,c,l){var k,g;g=k=a.element;b=b||1;do if(a=k[0>b?"previousSibling":"nextSibling"]){do if((k=a)&&-1<(k.className+" ").indexOf(c+" ")){g=k;b+=0>b?1:-1;break}while(a=(!l||!k.hidden)&&k[0>b?"lastChild":"firstChild"])}else if(k=k.parentNode,
k===this.bodyNode||k===this.headerNode)break;while(b);return g},up:function(a,b,c){return this.row(this._move(a,-(b||1),"dgrid-row",c))},down:function(a,b,c){return this.row(this._move(a,b||1,"dgrid-row",c))},scrollTo:e("touch")?function(){return this.inherited(arguments)}:function(a){"undefined"!==typeof a.x&&(this.bodyNode.scrollLeft=a.x);"undefined"!==typeof a.y&&(this.bodyNode.scrollTop=a.y)},getScrollPosition:e("touch")?function(){return this.inherited(arguments)}:function(){return{x:this.bodyNode.scrollLeft,
y:this.bodyNode.scrollTop}},get:function(a){var b="_get"+a.charAt(0).toUpperCase()+a.slice(1);return"function"===typeof this[b]?this[b].apply(this,[].slice.call(arguments,1)):this[a]},set:function(a,b){if("object"===typeof a)for(var c in a)this.set(c,a[c]);else c="_set"+a.charAt(0).toUpperCase()+a.slice(1),"function"===typeof this[c]?this[c].apply(this,[].slice.call(arguments,1)):this[a]=b;return this},_getClass:b,_setClass:c,_getClassName:b,_setClassName:c,_setSort:function(a,b){this._sort="string"!=
typeof a?a:[{attribute:a,descending:b}];this.refresh();this._lastCollection&&(a.length&&("string"!=typeof a&&(b=a[0].descending,a=a[0].attribute),this._lastCollection.sort(function(c,l){var k=c[a],g=l[a];void 0===k&&(k="");void 0===g&&(g="");return k==g?0:k>g==!b?1:-1})),this.renderArray(this._lastCollection))},sort:function(a,b){r.deprecated("sort(...)",'use set("sort", ...) instead',"dgrid 1.0");this.set("sort",a,b)},_getSort:function(){return this._sort},_setShowHeader:function(a){var b=this.headerNode;
this.showHeader=a;f(b,(a?"!":".")+"dgrid-header-hidden");this.renderHeader();this.resize();a&&(b.scrollLeft=this.getScrollPosition().x)},setShowHeader:function(a){r.deprecated("setShowHeader(...)",'use set("showHeader", ...) instead',"dgrid 1.0");this.set("showHeader",a)},_setShowFooter:function(a){this.showFooter=a;f(this.footerNode,(a?"!":".")+"dgrid-footer-hidden");this.resize()}})})},"dgrid/util/misc":function(){define([],function(){var t={defaultDelay:15,throttle:function(r,s,h){var e=!1;h=h||
t.defaultDelay;return function(){e||(e=!0,r.apply(s,arguments),setTimeout(function(){e=!1},h))}},throttleDelayed:function(r,s,h){var e=!1;h=h||t.defaultDelay;return function(){if(!e){e=!0;var n=arguments;setTimeout(function(){e=!1;r.apply(s,n)},h)}}},debounce:function(r,s,h){var e;h=h||t.defaultDelay;return function(){e&&(clearTimeout(e),e=null);var n=arguments;e=setTimeout(function(){r.apply(s,n)},h)}}};return t})},"xstyle/has-class":function(){define(["dojo/has"],function(t){var r={};return function(){for(var s,
h=arguments,e=0;e<h.length;e++)if(s=h[e],!r[s]){r[s]=!0;var n=s.match(/^(no-)?(.+?)((-[\d\.]+)(-[\d\.]+)?)?$/),w=t(n[2]),m=-n[4];if((0<m?m<=w&&(-n[5]||m)>=w:!!w)==!n[1])document.documentElement.className+=" has-"+s}}})},"xstyle/css":function(){define(["require"],function(t){var r=window.cssCache||(window.cssCache={});return{load:function(s,h,e,n){var w=h.toUrl(s);if(r[w])return createStyleSheet(r[w]);n=document.documentElement;var m=n.insertBefore(document.createElement("div"),n.firstChild);m.id=
h.toAbsMid(s).replace(/\//g,"-").replace(/\..*/,"")+"-loaded";s=(m.currentStyle||getComputedStyle(m,null)).display;n.removeChild(m);if("none"==s)return e();t(["./load-css"],function(f){f(w,e)})},pluginBuilder:"xstyle/css-builder"}})},"dgrid/OnDemandList":function(){define("./List ./_StoreMixin dojo/_base/declare dojo/_base/lang dojo/_base/Deferred dojo/on ./util/misc put-selector/put".split(" "),function(t,r,s,h,e,n,w,m){return s([t,r],{minRowsPerPage:25,maxRowsPerPage:250,maxEmptySpace:Infinity,
bufferRows:10,farOffRemoval:2E3,rowHeight:22,queryRowsOverlap:1,pagingDelay:w.defaultDelay,postCreate:function(){this.inherited(arguments);var f=this;n(this.bodyNode,"scroll",w.throttleDelayed(function(c){f._processScroll(c)},null,this.pagingDelay))},renderQuery:function(f,c,b){var a={query:f,count:0,node:c,options:b};if(!c){var p={node:m(this.contentNode,"div.dgrid-preload",{rowIndex:0}),count:0,query:f,next:a,options:b};a.node=c=m(this.contentNode,"div.dgrid-preload");a.previous=p}c.rowIndex=this.minRowsPerPage;
(p=this.preload)?((a.next=p.next)&&this.bodyNode.scrollTop>=p.node.offsetTop?a.previous=p:(a.next=p,a.previous=p.previous),a.previous.next=a,a.next.previous=a):this.preload=a;var g=m(c,"-div.dgrid-loading");m(g,"div.dgrid-below").innerHTML=this.loadingMessage;b=h.mixin(this.get("queryOptions"),b,{start:0,count:this.minRowsPerPage,query:f});var d=f(b),u=this;e.when(this.renderArray(d,c,b),function(b){return e.when(d.total||d.length,function(d){m(g,"!");var f=b.length;d=d||f;d||(u.noDataNode=m(u.contentNode,
"div.dgrid-no-data"),u.noDataNode.innerHTML=u.noDataMessage);for(var e=0,l=0;l<f;l++)e+=u._calcRowHeight(b[l]);f&&e&&(u.rowHeight=e/f);d-=f;a.count=d;c.rowIndex=f;d?c.style.height=Math.min(d*u.rowHeight,u.maxEmptySpace)+"px":c.style.display="none";u._processScroll();return b})});return d},refresh:function(){this.inherited(arguments);if(this.store){var f=this;this._trackError(function(){return f.renderQuery(function(c){return f.store.query(f.query,c)})})}},_calcRowHeight:function(f){var c=f.previousSibling;
return c&&c.offsetTop!=f.offsetTop?f.offsetHeight:0},lastScrollTop:0,_processScroll:function(f){function c(l,k,c,g){var d=a.farOffRemoval,f=l.node;if(k>2*d){for(var e,h=f[c],p=0,q=0,u=[];e=h;){var A=a._calcRowHeight(e);if(p+A+d>k||0>h.className.indexOf("dgrid-row")&&0>h.className.indexOf("dgrid-loading"))break;var h=e[c],n,x=e.observerIndex;if(x!=n&&-1<n){var v=a.observers,r=v[n];r&&r.cancel();v[n]=0}p+=A;q+=e.count||1;n=x;a.removeRow(e,!0);u.push(e)}l.count+=q;g?(f.rowIndex-=q,b(l)):f.style.height=
f.offsetHeight+p+"px";var s=m("div");for(l=0;l<u.length;l++)m(s,u[l]);setTimeout(function(){m(s,"!")},1)}}function b(b,l){b.node.style.height=Math.min(b.count*a.rowHeight,l?Infinity:a.maxEmptySpace)+"px"}var a=this,p=a.bodyNode;f=f&&f.scrollTop||p.scrollTop;var g=p.offsetHeight+f,d,u,q=a.preload,n=a.lastScrollTop,r=a.bufferRows*a.rowHeight,s=r-a.rowHeight;for(a.lastScrollTop=f;q&&!q.node.offsetWidth;)q=q.previous;for(;q&&q!=d;){d=a.preload;a.preload=q;u=q.node;var l=u.offsetTop;if(g+1+s<l){do q=q.previous;
while(q&&!q.node.offsetWidth)}else if(f-1-s>l+u.offsetHeight){do q=q.next;while(q&&!q.node.offsetWidth)}else{var k=((u.rowIndex?f-r:g)-l)/a.rowHeight,l=(g-f+2*r)/a.rowHeight,A=Math.max(Math.min((f-n)*a.rowHeight,a.maxRowsPerPage/2),a.maxRowsPerPage/-2),l=l+Math.min(Math.abs(A),10);0==u.rowIndex&&(k-=l);k=Math.max(k,0);10>k&&(0<k&&l+k<a.maxRowsPerPage)&&(l+=Math.max(0,k),k=0);l=Math.min(Math.max(l,a.minRowsPerPage),a.maxRowsPerPage,q.count);if(0==l)break;var l=Math.ceil(l),k=Math.min(Math.floor(k),
q.count-l),x=h.mixin(a.get("queryOptions"),q.options);q.count-=l;var t=u,w,E=a.queryRowsOverlap;if(A=0<u.rowIndex&&q){var B=q.previous;B&&(c(B,f-(B.node.offsetTop+B.node.offsetHeight),"nextSibling"),0<k&&B.node==u.previousSibling?(k=Math.min(q.count,k),q.previous.count+=k,b(q.previous,!0),q.count-=k,u.rowIndex+=k,E=0):l+=k);x.start=u.rowIndex-E;u.rowIndex+=l}else q.next&&(c(q.next,q.next.node.offsetTop-g,"previousSibling",!0),t=u.nextSibling,t==q.next.node?(q.next.count+=q.count-k,q.next.node.rowIndex=
k+l,b(q.next),q.count=k,E=0):w=!0),x.start=q.count;x.count=Math.min(l+E,a.maxRowsPerPage);w&&(w=t.offsetTop);b(q);u=m(t,"-div.dgrid-loading[style\x3dheight:"+l*a.rowHeight+"px]");m(u,"div.dgrid-"+(A?"below":"above")).innerHTML=a.loadingMessage;u.count=l;x.query=q.query;var F=q.query(x);if(void 0===a._trackError(function(){return F}))break;(function(l,k,c,g,d){e.when(a.renderArray(d,l,x),function(){t=l.nextSibling;m(l,"!");if(g&&t){var k=a.getScrollPosition();a.scrollTo({x:k.x,y:k.y+t.offsetTop-g,
preserveMomentum:!0})}c&&e.when(d.total||d.length,function(a){c.count=a-c.node.rowIndex;b(c)});a._processScroll()})}).call(this,u,p,A,w,F);q=q.previous}}}})})},"dgrid/_StoreMixin":function(){define("dojo/_base/kernel dojo/_base/declare dojo/_base/lang dojo/_base/Deferred dojo/on put-selector/put".split(" "),function(t,r,s,h,e,n){function w(m){"object"!==typeof m&&(m=Error(m));m.grid=this;e.emit(this.domNode,"dgrid-error",{grid:this,error:m,cancelable:!0,bubbles:!0})&&console.error(m)}return r(null,
{store:null,query:null,queryOptions:null,getBeforePut:!0,noDataMessage:"",loadingMessage:"",constructor:function(){this.query={};this.queryOptions={};this.dirty={};this._updating={}},_configColumn:function(e){e.set&&(this._columnsWithSet||(this._columnsWithSet={}),this._columnsWithSet[e.field]=e)},_configColumns:function(){this._columnsWithSet=null;return this.inherited(arguments)},_setStore:function(e,f,c){this.store=e;this.dirty={};this.set("query",f,c)},_setQuery:function(e,f){var c=f&&f.sort;
this.query=void 0!==e?e:this.query;this.queryOptions=f||this.queryOptions;c?this.set("sort",c):this.refresh()},setStore:function(e,f,c){t.deprecated("setStore(...)",'use set("store", ...) instead',"dgrid 1.0");this.set("store",e,f,c)},setQuery:function(e,f){t.deprecated("setQuery(...)",'use set("query", ...) instead',"dgrid 1.0");this.set("query",e,f)},_getQueryOptions:function(){var e=s.delegate(this.queryOptions,{});this._sort.length&&(e.sort=this._sort);return e},_getQuery:function(){var e=this.query;
return"object"==typeof e&&null!=e?s.delegate(e,{}):e},_setSort:function(e,f){this.store&&(this._lastCollection=null);this.inherited(arguments)},insertRow:function(e,f,c,b,a){var h=this.store,g=this.dirty,h=h&&h.getIdentity(e),d;h in g&&!(h in this._updating)&&(d=g[h]);d&&(e=s.delegate(e,d));return this.inherited(arguments)},updateDirty:function(e,f,c){var b=this.dirty,a=b[e];a||(a=b[e]={});a[f]=c},setDirty:function(e,f,c){t.deprecated("setDirty(...)","use updateDirty() instead","dgrid 1.0");this.updateDirty(e,
f,c)},save:function(){function e(a,g){return function(d){var e=f._columnsWithSet,l=f._updating,k,m;for(k in g)d[k]=g[k];if(e)for(k in e)m=e[k].set(d),void 0!==m&&(d[k]=m);l[a]=!0;return h.when(c.put(d),function(){delete b[a];delete l[a]})}}var f=this,c=this.store,b=this.dirty,a=new h,p=a.promise,g=function(a){var b;return f.getBeforePut||!(b=f.row(a).data)?function(){return c.get(a)}:function(){return b}},d;for(d in b)var u=e(d,b[d]),p=p.then(g(d)).then(u);a.resolve();return p},revert:function(){this.dirty=
{};this.refresh()},_trackError:function(e){var f;"string"==typeof e&&(e=s.hitch(this,e));try{f=e()}catch(c){w.call(this,c)}return h.when(f,null,s.hitch(this,w))},newRow:function(){this.noDataNode&&(n(this.noDataNode,"!"),delete this.noDataNode);return this.inherited(arguments)},removeRow:function(e,f){var c={element:e};!f&&(this.noDataMessage&&this.up(c).element===e&&this.down(c).element===e)&&(this.noDataNode=n(this.contentNode,"div.dgrid-no-data"),this.noDataNode.innerHTML=this.noDataMessage);return this.inherited(arguments)}})})},
"dgrid/Keyboard":function(){define("dojo/_base/declare dojo/aspect dojo/on ./List dojo/_base/lang dojo/has put-selector/put dojo/_base/Deferred dojo/_base/sniff".split(" "),function(t,r,s,h,e,n,w,m){var f={checkbox:1,radio:1,button:1},c=/\bdgrid-cell\b/,b=/\bdgrid-row\b/;n.add("dom-contains",function(){return!!document.createElement("a").contains});return t(null,{pageSkip:10,tabIndex:0,postCreate:function(){function a(a){var b=a.target;return b.type&&(!f[b.type]||32==a.keyCode)}function h(d){function f(a,
b,k){var c=g.cellNavigation?"cell":"row",d=g[c](a);if(a=d&&d.element)b=e.mixin({grid:g},b),b.type&&(b.parentType=b.type),b.bubbles||(b.bubbles=!0),w(p,"!dgrid-focus[!tabIndex]"),p&&(8>n("ie")&&(p.style.position=""),b[c]=g[c](p),s.emit(a,"dgrid-cellfocusout",b)),p=a,b[c]=d,k||(8>n("ie")&&(a.style.position="relative"),a.tabIndex=g.tabIndex,a.focus()),w(a,".dgrid-focus"),s.emit(p,"dgrid-cellfocusin",b)}for(var q=g.cellNavigation?c:b,p=d,t;(t=p.firstChild)&&!q.test(t.className);)p=t;t&&(p=t);d===g.contentNode?
r.after(g,"renderArray",function(a){return m.when(a,function(a){var b;if(b=q.test(p.className))b=p,b=n("dom-contains")?d.contains(b):d.compareDocumentPosition(b)&8;if(b)return a;b=0;for(var c=d.getElementsByTagName("*"),e;e=c[b];++b)if(q.test(e.className)){p=e;break}p.tabIndex=g.tabIndex;return a})}):q.test(p.className)&&(p.tabIndex=g.tabIndex);s(d,"mousedown",function(b){a(b)||f(b.target,b)});s(d,"keydown",function(b){if(!b.metaKey&&!b.altKey){var l=b.keyCode;if(!a(b)){var c={32:0,33:-g.pageSkip,
34:g.pageSkip,37:-1,38:-1,39:1,40:1,35:1E4,36:-1E4}[l];if(!isNaN(c)){var e,d=g.cell(p);if(37==l||39==l){if(!g.cellNavigation)return;l="right"}else l="down",e=d&&d.column&&d.column.id,d=g.row(p);c&&(d=d&&g[l](d,c,!0));if(c=d&&d.element){e&&(c=g.cell(c,e).element);if(g.cellNavigation){e=c.getElementsByTagName("input");for(var h,d=0;d<e.length;d++)if(l=e[d],(-1!=l.tabIndex||"lastValue"in l)&&!l.disabled){8>n("ie")&&(l.style.position="relative");l.focus();8>n("ie")&&(l.style.position="");h=!0;break}}f(c,
b,h)}b.preventDefault()}}}});return function(a){a=a||p;f(a,{target:a})}}this.inherited(arguments);var g=this;this.tabableHeader&&(this.focusHeader=h(this.headerNode));this.focus=h(this.contentNode)}})})},"dgrid/Selection":function(){define("dojo/_base/kernel dojo/_base/declare dojo/_base/Deferred dojo/on dojo/has dojo/aspect ./List dojo/has!touch?./util/touch put-selector/put dojo/query".split(" "),function(t,r,s,h,e,n,w,m,f){var c=e("mac")?"metaKey":"ctrlKey";return r(null,{selectionDelegate:".dgrid-row",
selectionEvents:"mousedown,mouseup,dgrid-cellfocusin",deselectOnRefresh:!0,allowSelectAll:!1,create:function(){this.selection={};return this.inherited(arguments)},postCreate:function(){this.inherited(arguments);this._initSelectionEvents()},selection:{},selectionMode:"extended",_setSelectionMode:function(b){b!=this.selectionMode&&(this.clearSelection(),this.selectionMode=b)},setSelectionMode:function(b){t.deprecated("setSelectionMode(...)",'use set("selectionMode", ...) instead',"dgrid 1.0");this.set("selectionMode",
b)},_handleSelect:function(b,a){if(!("none"==this.selectionMode||"dgrid-cellfocusin"==b.type&&"mousedown"==b.parentType||"mouseup"==b.type&&a!=this._waitForMouseUp)){this._waitForMouseUp=null;this._selectionTriggerEvent=b;var e=!b.keyCode?b[c]:b.ctrlKey;if(!b.keyCode||!b.ctrlKey||32==b.keyCode){var g=this.selectionMode,d=this.row(a),f=this._lastSelected;if("single"==g)f===a?this.select(a,null,!e||!this.isSelected(a)):(this.clearSelection(),this.select(a),this._lastSelected=a);else if(this.selection[d.id]&&
!b.shiftKey&&"mousedown"==b.type)this._waitForMouseUp=a;else{var h;(2!=b.button&&"extended"==g&&!e||2==b.button&&!this.selection[d.id])&&this.clearSelection(d.id,!0);b.shiftKey||(f=h=e?null:void 0);this.select(a,f,h);f||(this._lastSelected=a)}!b.keyCode&&(b.shiftKey||e)&&b.preventDefault()}this._selectionTriggerEvent=null}},_initSelectionEvents:function(){function b(b){a._handleSelect(b,this)}var a=this,f=this.selectionDelegate;h(this.domNode,"selectstart",function(a){var b=a.target&&a.target.tagName;
"INPUT"!=b&&"TEXTAREA"!=b&&a.preventDefault()});e("touch")?h(this.contentNode,m.selector(f,m.tap),function(b){a._handleSelect(b,this)}):h(this.contentNode,h.selector(f,this.selectionEvents),b);if(this.allowSelectAll)this.on("keydown",function(b){b[c]&&65==b.keyCode&&(b.preventDefault(),a[a.allSelected?"clearSelection":"selectAll"]())});n.before(this,"removeRow",function(a,b){var c;b||(c=this.row(a))&&c.id in this.selection&&this.deselect(a)})},allowSelect:function(b){return!0},_selectionEventQueue:function(b,
a){var c=this,e="dgrid-"+(b?"select":"deselect"),d=this[e],f=this._selectionTriggerEvent;f&&(f=f.type);if(d)return d;setTimeout(this._fireSelectionEvent=function(){if(d){var b={bubbles:!0,grid:c};f&&(b.parentType=f);b[a]=d;h.emit(c.contentNode,e,b);d=null;delete c[e]}},0);return d=this[e]=[]},select:function(b,a,c){void 0===c&&(c=!0);b.element||(b=this.row(b));if(this.allowSelect(b)){var e=this.selection,d=e[b.id];null===c&&(c=!d);var h=b.element;!c&&!this.allSelected?delete this.selection[b.id]:
e[b.id]=c;h&&(c?f(h,".dgrid-selected.ui-state-active"):f(h,"!dgrid-selected!ui-state-active"));c!=d&&h&&this._selectionEventQueue(c,"rows").push(b);if(a){a.element||(a=this.row(a));a=a.element;c=b.element;for(c=a&&(a.compareDocumentPosition?2==a.compareDocumentPosition(c):a.sourceIndex>c.sourceIndex)?"down":"up";b.element!=a&&(b=this[c](b));)this.select(b)}}},deselect:function(b,a){this.select(b,a,!1)},clearSelection:function(b,a){this.allSelected=!1;for(var c in this.selection)b!==c&&this.deselect(c);
a||(this._lastSelected=null)},selectAll:function(){this.allSelected=!0;this.selection={};for(var b in this._rowIdToObject){var a=this.row(this._rowIdToObject[b]);this.select(a.id)}},isSelected:function(b){if(!b)return!1;b.element||(b=this.row(b));return!!this.selection[b.id]},refresh:function(){this.deselectOnRefresh&&(this.clearSelection(),this._fireSelectionEvent&&this._fireSelectionEvent());this._lastSelected=null;this.inherited(arguments)},renderArray:function(){var b=this,a=this.inherited(arguments);
s.when(a,function(a){var c=b.selection,e,f,h;for(e=0;e<a.length;e++)f=b.row(a[e]),(h=f.id in c?c[f.id]:b.allSelected)&&b.select(f,null,h)});return a}})})},"dgrid/editor":function(){define("dojo/_base/kernel dojo/_base/lang dojo/_base/array dojo/_base/Deferred dojo/on dojo/aspect dojo/has ./Grid put-selector/put dojo/_base/sniff".split(" "),function(t,r,s,h,e,n,w,m,f){function c(a,b){a.value=b;if("radio"==a.type||"checkbox"==a.type)a.checked=!!b}function b(a,b){if("number"==typeof b)a=isNaN(a)?a:parseFloat(a);
else if("boolean"==typeof b)a="true"==a?!0:"false"==a?!1:a;else if(b instanceof Date){var c=new Date(a);a=isNaN(c.getTime())?a:c}return a}function a(a,b,d,f,g){var h,m,n;if(!(d>=f&&d<=f)&&(h=a.cell(b),m=h.row,n=h.column,n.field&&m))if(h={grid:a,cell:h,rowId:m.id,oldValue:d,value:f,bubbles:!0,cancelable:!0},g&&g.type&&(h.parentType=g.type),e.emit(b,"dgrid-datachange",h))a.updateDirty&&(a.updateDirty(m.id,n.field,f),n.autoSave&&setTimeout(function(){a._trackError("save")},0));else{var q;(q=b.widget)?
(q._dgridIgnoreChange=!0,q.set("value",d),setTimeout(function(){q._dgridIgnoreChange=!1},0)):(q=b.input)&&c(q,d);return d}return f}function p(c,e,d,f){if(!d.isValid||d.isValid()){e=a;var g=(d.domNode||d).parentNode,h=v?y:d._dgridLastValue,m;m="function"==typeof d.get?b(d.get("value")):b(d["checkbox"==d.type||"radio"==d.type?"checked":"value"]);c=e(c,g,h,m,f);v?y=c:d._dgridLastValue=c}}function g(a){var b=a.editor,c=a.editOn,d=a.grid,g="string"!=typeof b,h,m,n;h=a.editorArgs||{};"function"==typeof h&&
(h=h.call(d,a));if(g)m=new b(h),g=m.focusNode||m.domNode,g.className+=" dgrid-input",m.connect(m,c?"onBlur":"onChange",function(){m._dgridIgnoreChange||p(d,a,this,{type:"widget"})});else if(n=function(b){var c=b.target;"_dgridLastValue"in c&&-1<c.className.indexOf("dgrid-input")&&p(d,a,c,b)},a.grid._hasInputListener||(d._hasInputListener=!0,d.on("change",function(a){n(a)})),m=g=f(("textarea"==b?"textarea":"input[type\x3d"+b+"]")+".dgrid-input",r.mixin({name:a.field,tabIndex:isNaN(a.tabIndex)?-1:a.tabIndex},
h)),9>w("ie")||w("ie")&&0)"radio"==b||"checkbox"==b?e(m,"click",function(a){n(a)}):e(m,"change",function(a){n(a)});e(g,"mousedown",function(a){a.stopPropagation()});return m}function d(a,b){var d=g(a),h=d.domNode||d,n=d.focusNode||h,q=d.domNode?function(){d.set("value",d._dgridLastValue)}:function(){c(d,d._dgridLastValue);p(a.grid,a,d)};e(n,"keydown",function(b){b=b.keyCode||b.which;27==b?(q(),y=d._dgridLastValue,n.blur()):13==b&&!1!==a.dismissOnEnter&&n.blur()});(a._editorBlurHandle=e.pausable(d,
"blur",function(){var b=h.parentNode;a.grid.cell(h);var c=b.children.length-1,d={alreadyHooked:!0};for(b.removeChild(h);c--;)f(b.firstChild,"!");m.appendIfNode(b,a.renderCell(a.grid.row(b).data,y,b,z?r.delegate(d,z):d));v=y=z=null;a._editorBlurHandle.pause()})).pause();return d}function u(a,b,d,e){(b=a.domNode)||c(a,e);d.innerHTML="";f(d,a.domNode||a);b&&(a._started||a.startup(),a._dgridIgnoreChange=!0,a.set("value",e),setTimeout(function(){a._dgridIgnoreChange=!1},0));a._dgridLastValue=e;v&&(y=e)}
function q(a){var b,c,d,e,f,g;a.column||(a=this.cell(a));b=a.column;e=b.field;c=a.element.contents||a.element;if(f=b.editorInstance){if(v!=c&&(!b.canEdit||b.canEdit(a.row.data,d)))return v=c,a=a.row,d=(d=this.dirty&&this.dirty[a.id])&&e in d?d[e]:b.get?b.get(a.data):a.data[e],u(b.editorInstance,b,c,d),g=new h,setTimeout(function(){f.focus&&f.focus();b._editorBlurHandle&&b._editorBlurHandle.resume();g.resolve(f)},0),g.promise}else if(b.editor&&(f=c.widget||c.input))return g=new h,f.focus&&f.focus(),
g.resolve(f),g.promise;return null}var v,y,z;return function(a,b,c){var f=a.renderCell||m.defaultRenderCell,h=[],p;a||(a={});a.editor=b=b||a.editor||"text";a.editOn=c=c||a.editOn;p="string"!=typeof b;a.widgetArgs&&(t.deprecated("column.widgetArgs","use column.editorArgs instead","dgrid 1.0"),a.editorArgs=a.widgetArgs);n.after(a,"init",c?function(){var b=a.grid;b.edit||(b.edit=q);a.editorInstance=d(a,f)}:function(){var b=a.grid;b.edit||(b.edit=q);p&&h.push(n.before(b,"removeRow",function(c){c=b.cell(c,
a.id).element;(c=(c.contents||c).widget)&&c.destroyRecursive()}))});n.after(a,"destroy",function(){s.forEach(h,function(a){a.remove()});a._editorBlurHandle&&a._editorBlurHandle.remove();c&&p&&a.editorInstance.destroyRecursive()});a.renderCell=c?function(b,d,h,g){if(!g||!g.alreadyHooked)e("TD"==h.tagName?h:h.parentNode,c,function(){z=g;a.grid.edit(this)});return f.call(a,b,d,h,g)}:function(b,c,d,e){if(!a.canEdit||a.canEdit(b,c))b=g(a),u(b,a,d,c),d[p?"widget":"input"]=b;else return f.call(a,b,c,d,e)};
return a}})},"moment/moment":function(){define([],function(){function t(a,b,c,d){var e=c.lang();return e[a].call?e[a](c,d):e[a][b]}function r(a,b){return function(c){return w(a.call(this,c),b)}}function s(a){return function(b){b=a.call(this,b);return b+this.lang().ordinal(b)}}function h(a,b,c){this._d=a;this._isUTC=!!b;this._a=a._a||null;this._lang=c||!1}function e(a){var b=this._data={},c=a.years||a.y||0,d=a.months||a.M||0,e=a.weeks||a.w||0,f=a.days||a.d||0,h=a.hours||a.h||0,g=a.minutes||a.m||0,
k=a.seconds||a.s||0;a=a.milliseconds||a.ms||0;this._milliseconds=a+1E3*k+6E4*g+36E5*h;this._days=f+7*e;this._months=d+12*c;b.milliseconds=a%1E3;k+=n(a/1E3);b.seconds=k%60;g+=n(k/60);b.minutes=g%60;h+=n(g/60);b.hours=h%24;f+=n(h/24);f+=7*e;b.days=f%30;d+=n(f/30);b.months=d%12;c+=n(d/12);b.years=c;this._lang=!1}function n(a){return 0>a?Math.ceil(a):Math.floor(a)}function w(a,b){for(var c=a+"";c.length<b;)c="0"+c;return c}function m(a,b,c){var d=b._milliseconds,e=b._days;b=b._months;d&&a._d.setTime(+a+
d*c);e&&a.date(a.date()+e*c);b&&(d=a.date(),a.date(1).month(a.month()+b*c).date(Math.min(d,a.daysInMonth())))}function f(a){return"[object Array]"===Object.prototype.toString.call(a)}function c(a,b){var c=Math.min(a.length,b.length),d=Math.abs(a.length-b.length),e=0,f;for(f=0;f<c;f++)~~a[f]!==~~b[f]&&e++;return e+d}function b(a,b,c,d){var e,f=[];for(e=0;7>e;e++)f[e]=a[e]=null==a[e]?2===e?1:0:a[e];a[7]=f[7]=b;null!=a[8]&&(f[8]=a[8]);a[3]+=c||0;a[4]+=d||0;c=new Date(0);b?(c.setUTCFullYear(a[0],a[1],
a[2]),c.setUTCHours(a[3],a[4],a[5],a[6])):(c.setFullYear(a[0],a[1],a[2]),c.setHours(a[3],a[4],a[5],a[6]));c._a=f;return c}function a(a,b){var c,d,e=[];!b&&E&&(b=require("./lang/"+a));for(c=0;c<B.length;c++)b[B[c]]=b[B[c]]||D.en[B[c]];for(c=0;12>c;c++)d=k([2E3,c]),e[c]=RegExp("^"+(b.months[c]||b.months(d,""))+"|^"+(b.monthsShort[c]||b.monthsShort(d,"")).replace(".",""),"i");b.monthsParse=b.monthsParse||e;return D[a]=b}function p(b){return(b="string"===typeof b&&b||b&&b._lang||null)?D[b]||a(b):k}function g(a){var b=
a.match(M),c,d;c=0;for(d=b.length;c<d;c++)b[c]=C[b[c]]?C[b[c]]:b[c].match(/\[.*\]/)?b[c].replace(/^\[|\]$/g,""):b[c].replace(/\\/g,"");return function(e){var f="";for(c=0;c<d;c++)f+="function"===typeof b[c].call?b[c].call(e,a):b[c];return f}}function d(a,b){function c(b){return a.lang().longDateFormat[b]||b}for(var d=5;d--&&N.test(b);)b=b.replace(N,c);J[b]||(J[b]=g(b));return J[b](a)}function u(a){switch(a){case "DDDD":return T;case "YYYY":return U;case "S":case "SS":case "SSS":case "DDD":return S;
case "MMM":case "MMMM":case "dd":case "ddd":case "dddd":case "a":case "A":return V;case "Z":case "ZZ":return G;case "T":return W;case "MM":case "DD":case "YY":case "HH":case "hh":case "mm":case "ss":case "M":case "D":case "d":case "H":case "h":case "m":case "s":return R;default:return RegExp(a.replace("\\",""))}}function q(a,c){var d=[0,0,1,0,0,0,0],e={tzh:0,tzm:0},f=c.match(M),h,g;for(h=0;h<f.length;h++)if((g=(u(f[h]).exec(a)||[])[0])&&(a=a.slice(a.indexOf(g)+g.length)),C[f[h]]){var k=d,l=e,m=void 0,
n=void 0;switch(f[h]){case "M":case "MM":k[1]=null==g?0:~~g-1;break;case "MMM":case "MMMM":for(m=0;12>m;m++)if(p().monthsParse[m].test(g)){k[1]=m;n=!0;break}n||(k[8]=!1);break;case "D":case "DD":case "DDD":case "DDDD":null!=g&&(k[2]=~~g);break;case "YY":k[0]=~~g+(70<~~g?1900:2E3);break;case "YYYY":k[0]=~~Math.abs(g);break;case "a":case "A":l.isPm="pm"===(g+"").toLowerCase();break;case "H":case "HH":case "h":case "hh":k[3]=~~g;break;case "m":case "mm":k[4]=~~g;break;case "s":case "ss":k[5]=~~g;break;
case "S":case "SS":case "SSS":k[6]=~~(1E3*("0."+g));break;case "Z":case "ZZ":l.isUTC=!0;if((m=(g+"").match(Y))&&m[1])l.tzh=~~m[1];m&&m[2]&&(l.tzm=~~m[2]);m&&"+"===m[0]&&(l.tzh=-l.tzh,l.tzm=-l.tzm)}null==g&&(k[8]=!1)}e.isPm&&12>d[3]&&(d[3]+=12);!1===e.isPm&&12===d[3]&&(d[3]=0);return b(d,e.isUTC,e.tzh,e.tzm)}function v(a,b,c,d,e){e=e.relativeTime[a];return"function"===typeof e?e(b||1,!!c,a,d):e.replace(/%d/i,b||1)}function y(a,b){k.fn[a]=function(a){var c=this._isUTC?"UTC":"";return null!=a?(this._d["set"+
c+b](a),this):this._d["get"+c+b]()}}function z(a){k.duration.fn[a]=function(){return this._data[a]}}function l(a,b){k.duration.fn["as"+a]=function(){return+this/b}}for(var k,A=Math.round,x,D={},K="en",E="undefined"!==typeof module&&module.exports,B="months monthsShort weekdays weekdaysShort weekdaysMin longDateFormat calendar relativeTime ordinal meridiem".split(" "),F=/^\/?Date\((\-?\d+)/i,M=/(\[[^\[]*\])|(\\)?(Mo|MM?M?M?|Do|DDDo|DD?D?D?|ddd?d?|do?|w[o|w]?|YYYY|YY|a|A|hh?|HH?|mm?|ss?|SS?S?|zz?|ZZ?|.)/g,
N=/(\[[^\[]*\])|(\\)?(LT|LL?L?L?)/g,L=/([0-9a-zA-Z\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]+)/gi,R=/\d\d?/,S=/\d{1,3}/,T=/\d{3}/,U=/\d{1,4}/,V=/[0-9a-z\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]+/i,G=/Z|[\+\-]\d\d:?\d\d/i,W=/T/i,X=/^\s*\d{4}-\d\d-\d\d(T(\d\d(:\d\d(:\d\d(\.\d\d?\d?)?)?)?)?([\+\-]\d\d:?\d\d)?)?/,O=[["HH:mm:ss.S",/T\d\d:\d\d:\d\d\.\d{1,3}/],["HH:mm:ss",/T\d\d:\d\d:\d\d/],["HH:mm",/T\d\d:\d\d/],["HH",/T\d\d/]],Y=/([\+\-]|\d\d)/gi,H="Month Date Hours Minutes Seconds Milliseconds".split(" "),
I={Milliseconds:1,Seconds:1E3,Minutes:6E4,Hours:36E5,Days:864E5,Months:2592E6,Years:31536E6},J={},P=["DDD","w","M","D","d"],Q="MDHhmsw".split(""),C={M:function(){return this.month()+1},MMM:function(a){return t("monthsShort",this.month(),this,a)},MMMM:function(a){return t("months",this.month(),this,a)},D:function(){return this.date()},DDD:function(){var a=new Date(this.year(),this.month(),this.date()),b=new Date(this.year(),0,1);return~~((a-b)/864E5+1.5)},d:function(){return this.day()},dd:function(a){return t("weekdaysMin",
this.day(),this,a)},ddd:function(a){return t("weekdaysShort",this.day(),this,a)},dddd:function(a){return t("weekdays",this.day(),this,a)},w:function(){var a=new Date(this.year(),this.month(),this.date()-this.day()+5),b=new Date(a.getFullYear(),0,4);return~~((a-b)/864E5/7+1.5)},YY:function(){return w(this.year()%100,2)},YYYY:function(){return w(this.year(),4)},a:function(){return this.lang().meridiem(this.hours(),this.minutes(),!0)},A:function(){return this.lang().meridiem(this.hours(),this.minutes(),
!1)},H:function(){return this.hours()},h:function(){return this.hours()%12||12},m:function(){return this.minutes()},s:function(){return this.seconds()},S:function(){return~~(this.milliseconds()/100)},SS:function(){return w(~~(this.milliseconds()/10),2)},SSS:function(){return w(this.milliseconds(),3)},Z:function(){var a=-this.zone(),b="+";0>a&&(a=-a,b="-");return b+w(~~(a/60),2)+":"+w(~~a%60,2)},ZZ:function(){var a=-this.zone(),b="+";0>a&&(a=-a,b="-");return b+w(~~(10*a/6),4)}};P.length;)x=P.pop(),
C[x+"o"]=s(C[x]);for(;Q.length;)x=Q.pop(),C[x+x]=r(C[x],2);C.DDDD=r(C.DDD,3);k=function(a,e){if(null===a||""===a)return null;var g;if(k.isMoment(a))return new h(new Date(+a._d),a._isUTC,a._lang);if(e)if(f(e)){var l=a.match(L)||[],m,n=99,p,r;for(p=0;p<e.length;p++)r=q(a,e[p]),m=d(new h(r),e[p]).match(L)||[],m=c(l,m),m<n&&(n=m,g=r)}else g=q(a,e);else if(g=F.exec(a),void 0===a)g=new Date;else if(g)g=new Date(+g[1]);else if(a instanceof Date)g=a;else if(f(a))g=b(a);else if("string"===typeof a)if(g="YYYY-MM-DDT",
X.exec(a)){for(l=0;4>l;l++)if(O[l][1].exec(a)){g+=O[l][0];break}g=G.exec(a)?q(a,g+" Z"):q(a,g)}else g=new Date(a);else g=new Date(a);return new h(g)};k.utc=function(a,c){if(f(a))return new h(b(a,!0),!0);"string"===typeof a&&!G.exec(a)&&(a+=" +0000",c&&(c+=" Z"));return k(a,c).utc()};k.unix=function(a){return k(1E3*a)};k.duration=function(a,b){var c=k.isDuration(a),d="number"===typeof a,f=c?a._data:d?{}:a;d&&(b?f[b]=a:f.milliseconds=a);d=new e(f);c&&(d._lang=a._lang);return d};k.humanizeDuration=function(a,
b,c){return k.duration(a,!0===b?null:b).humanize(!0===b?!0:c)};k.version="1.7.2";k.defaultFormat="YYYY-MM-DDTHH:mm:ssZ";k.lang=function(b,c){var d;if(!b)return K;(c||!D[b])&&a(b,c);if(D[b]){for(d=0;d<B.length;d++)k[B[d]]=D[b][B[d]];k.monthsParse=D[b].monthsParse;K=b}};k.langData=p;k.isMoment=function(a){return a instanceof h};k.isDuration=function(a){return a instanceof e};k.lang("en",{months:"January February March April May June July August September October November December".split(" "),monthsShort:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),
weekdays:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),weekdaysShort:"Sun Mon Tue Wed Thu Fri Sat".split(" "),weekdaysMin:"Su Mo Tu We Th Fr Sa".split(" "),longDateFormat:{LT:"h:mm A",L:"MM/DD/YYYY",LL:"MMMM D YYYY",LLL:"MMMM D YYYY LT",LLLL:"dddd, MMMM D YYYY LT"},meridiem:function(a,b,c){return 11<a?c?"pm":"PM":c?"am":"AM"},calendar:{sameDay:"[Today at] LT",nextDay:"[Tomorrow at] LT",nextWeek:"dddd [at] LT",lastDay:"[Yesterday at] LT",lastWeek:"[last] dddd [at] LT",sameElse:"L"},
relativeTime:{future:"in %s",past:"%s ago",s:"a few seconds",m:"a minute",mm:"%d minutes",h:"an hour",hh:"%d hours",d:"a day",dd:"%d days",M:"a month",MM:"%d months",y:"a year",yy:"%d years"},ordinal:function(a){var b=a%10;return 1===~~(a%100/10)?"th":1===b?"st":2===b?"nd":3===b?"rd":"th"}});k.fn=h.prototype={clone:function(){return k(this)},valueOf:function(){return+this._d},unix:function(){return Math.floor(+this._d/1E3)},toString:function(){return this._d.toString()},toDate:function(){return this._d},
toArray:function(){return[this.year(),this.month(),this.date(),this.hours(),this.minutes(),this.seconds(),this.milliseconds(),!!this._isUTC]},isValid:function(){return this._a?null!=this._a[8]?!!this._a[8]:!c(this._a,(this._a[7]?k.utc(this._a):k(this._a)).toArray()):!isNaN(this._d.getTime())},utc:function(){this._isUTC=!0;return this},local:function(){this._isUTC=!1;return this},format:function(a){return d(this,a?a:k.defaultFormat)},add:function(a,b){var c=b?k.duration(+b,a):k.duration(a);m(this,
c,1);return this},subtract:function(a,b){var c=b?k.duration(+b,a):k.duration(a);m(this,c,-1);return this},diff:function(a,b,c){a=this._isUTC?k(a).utc():k(a).local();var d=6E4*(this.zone()-a.zone()),d=this._d-a._d-d,e=this.year()-a.year(),f=this.month()-a.month();a=this.date()-a.date();b="months"===b?12*e+f+a/30:"years"===b?e+(f+a/30)/12:"seconds"===b?d/1E3:"minutes"===b?d/6E4:"hours"===b?d/36E5:"days"===b?d/864E5:"weeks"===b?d/6048E5:d;return c?b:A(b)},from:function(a,b){return k.duration(this.diff(a)).lang(this._lang).humanize(!b)},
fromNow:function(a){return this.from(k(),a)},calendar:function(){var a=this.diff(k().sod(),"days",!0),b=this.lang().calendar,c=b.sameElse,a=-6>a?c:-1>a?b.lastWeek:0>a?b.lastDay:1>a?b.sameDay:2>a?b.nextDay:7>a?b.nextWeek:c;return this.format("function"===typeof a?a.apply(this):a)},isLeapYear:function(){var a=this.year();return 0===a%4&&0!==a%100||0===a%400},isDST:function(){return this.zone()<k([this.year()]).zone()||this.zone()<k([this.year(),5]).zone()},day:function(a){var b=this._isUTC?this._d.getUTCDay():
this._d.getDay();return null==a?b:this.add({d:a-b})},startOf:function(a){switch(a.replace(/s$/,"")){case "year":this.month(0);case "month":this.date(1);case "day":this.hours(0);case "hour":this.minutes(0);case "minute":this.seconds(0);case "second":this.milliseconds(0)}return this},endOf:function(a){return this.startOf(a).add(a.replace(/s?$/,"s"),1).subtract("ms",1)},sod:function(){return this.clone().startOf("day")},eod:function(){return this.clone().endOf("day")},zone:function(){return this._isUTC?
0:this._d.getTimezoneOffset()},daysInMonth:function(){return k.utc([this.year(),this.month()+1,0]).date()},lang:function(a){if(void 0===a)return p(this);this._lang=a;return this}};for(x=0;x<H.length;x++)y(H[x].toLowerCase(),H[x]);y("year","FullYear");k.duration.fn=e.prototype={weeks:function(){return n(this.days()/7)},valueOf:function(){return this._milliseconds+864E5*this._days+2592E6*this._months},humanize:function(a){var b=+this,c=this.lang().relativeTime,d;d=!a;var e=this.lang(),f=A(Math.abs(b)/
1E3),g=A(f/60),h=A(g/60),k=A(h/24),l=A(k/365),f=45>f&&["s",f]||1===g&&["m"]||45>g&&["mm",g]||1===h&&["h"]||22>h&&["hh",h]||1===k&&["d"]||25>=k&&["dd",k]||45>=k&&["M"]||345>k&&["MM",A(k/30)]||1===l&&["y"]||["yy",l];f[2]=d;f[3]=0<b;f[4]=e;d=v.apply({},f);b=0>=b?c.past:c.future;a&&(d="function"===typeof b?b(d):b.replace(/%s/i,d));return d},lang:k.fn.lang};for(x in I)I.hasOwnProperty(x)&&(l(x,I[x]),z(x.toLowerCase()));l("Weeks",6048E5);return k})}}});
define("dote-client/viewAdmin","dojo/_base/array dojo/_base/declare dojo/ready dojo/store/Cache dojo/store/Memory dgrid/OnDemandGrid dgrid/Keyboard dgrid/Selection dgrid/editor moment/moment ./store/JsonRest ./userControls ./widgetModules".split(" "),function(t,r,s,h,e,n,w,m,f,c,b,a){var p=h(new b({target:"/users/"}),new e),g=h(new b({target:"/topics/"}),new e);s(function(){a.start();var b=[{field:"id",label:"User ID"},f({field:"admin",label:"Admin Flag",editor:"checkbox",editOn:"dblclick",autoSave:!0}),
f({field:"owner",label:"Owner Flag",editor:"checkbox",editOn:"dblclick",autoSave:!0}),f({field:"committer",label:"Committer Flag",editor:"checkbox",editOn:"dblclick",autoSave:!0}),f({field:"attempts",label:"Attempts",editor:"text",editOn:"dblclick",autoSave:!0}),{field:"lastLogin",label:"Last Login",get:function(a){return a.lastLogin?c.unix(a.lastLogin).format("DD/MM/YY HH:mm"):null}}];(new r([n,w,m]))({columns:b,store:p},"userGrid");b=[{field:"id",label:"ID",formatter:function(a){return'\x3ca href\x3d"/topic/'+
a+'" target\x3d"_blank"\x3e'+a+"\x3c/a\x3e"}},{field:"title",label:"Title"},{field:"voters",sortable:!1,label:"Vote",get:function(a){var b=a.voters.length?0:null;t.forEach(a.voters,function(a){b+=a.vote});return 0<b&&null!==b?"+"+b:b}},{field:"author",label:"Author"},{field:"created",label:"Created",get:function(a){return c.unix(a.created).format("DD/MM/YY HH:mm")}},f({field:"owner",label:"Owner",editor:"text",editOn:"dblclick",autoSave:!0}),{field:"action",label:"Action"},{field:"actioned",label:"Actioned",
get:function(a){return a.actioned?c.unix(a.actioned).format("DD/MM/YY HH:mm"):null}},{field:"commentsCount",label:"Cmt"}];(new r([n,w,m]))({columns:b,store:g},"topicGrid")})});
//@ sourceMappingURL=viewAdmin.js.map